# batch config files aims to run prediction on full phone image 
# -> detect mobile boundary -> create patch and predict -> aggregate patch

model:
  path: "models/best_model/best_model.pth"
  device: "auto"
  threshold: 0.5

input:
  path: "tests/scratch_images_star/"
  image_extensions: [".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".tif"]
  max_samples: null

output:
  dir: "tests/inference_results/scratch_star"

processing:
  batch_mode: True
  new_images: False
  full_phone:
    enabled: True
    patch_size: 1024
    overlap: 0
    min_dirt_threshold: 0.01

logging:
  file: "logs/full_phone_batch_predictor_star.log"