# This config files aims to run prediction on patches with mask 

model:
  path: "models/best_model/best_model.pth"
  device: "auto"
  threshold: 0.5

input:
  path: "tests/patches/patch_000_x377_y728/"
  image_extensions: [".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".tif"]
  max_samples: null

output:
  dir: "tests/inference_results/patch_predictions"

processing:
  batch_mode: False
  new_images: False
  full_phone:
    enabled: False
    patch_size: 1024
    overlap: 0
    min_dirt_threshold: 0.01

logging:
  file: "logs/mask_predictor.log"